### ISSUE TITLE
Package losing sementic versioning

### ISSUE THREAD

**Issue by aboutandre** [beshanoe/update-by-scope#1]
Hi!

Thanks for the awesome package. This is saving me so much effort when working with distributed packages.

But there is this one package that is losing the semantic versioning to specify update type. Eg.:

Before:
```json
"dependencies": {
  "@awesomeproject/my_dep": "^1.0.4”,
}
```

After
```json
"dependencies": {
  "@awesomeproject/my_dep": "1.0.5",
}
```

Probably this is something on my end. Any hints of what I should be looking for?

I’m using NPM v6.9.0 and NodeJS v10.15.3.

Love from Hamburg!

**Comment by beshanoe** [comment]
Hey! Could you provide some steps to reproduce, what do you run?

**Comment by aboutandre** [comment]
While in the directory where the `package.json` is located:
```bash
npx update-by-scope @package-name npm i
```

Multiple packages get correctly updated, except one that always loses the `^`

**Comment by beshanoe** [comment]
Looks more like npm issue, cause update-by-scope is basically just running `npm i @awesomeproject/my_dep` in your case. Please check if this SO question helps https://stackoverflow.com/questions/54091452/why-does-npm-install-add-remove-caret-to-from-version-numbers

**Comment by aboutandre** [comment]
@beshanoe thanks for taking a look at this! 
This is indeed not a problem with _update-by-scope_, but somehow with NPM itself.

Just running `npm install @awesomepackage/my_dep@latest` indeed does the same.

The SO question sadly did not help me, this is affecting only one package in my case. In the SO question it was affecting all packages.

I asked a question in SO:
https://stackoverflow.com/questions/57392343/installing-package-with-latest-removes-semantic-versioning

I will be closing this issue for the moment since this is not being caused by _update-by-scope_.
