### ISSUE TITLE
options -n -c getting ignored

### ISSUE THREAD

**Issue by jnpmarques** [beshanoe/update-by-scope#18]
The options -n -c are getting ignored and the defaults are being used:

```
npx update-by-scope -n npm -c update @test-scope
Found 1 with scope "@test-scope":
[
  '@test-scope/web-components'
]
Executing "npm install @test-scope/web-components@latest"
...
```

Using 
SO: ubuntu 22.10
npm: 8.19.3

**Comment by jnpmarques** [comment]
[Added a pull request for a fix](https://github.com/beshanoe/update-by-scope/pull/19).

**Comment by beshanoe** [comment]
thanks José, good catch!
