### ISSUE TITLE
Command not actually doing anything

### ISSUE THREAD

**Issue by gs-scooter** [beshanoe/update-by-scope#4]
I tried updating all project packages within the @syncfusion scope using the following command:
`npx update-by-scope @syncfusion/`

This produces the following output:
```Found 9 with scope "@syncfusion/":
[
  '@syncfusion/ej2-angular-buttons',
  '@syncfusion/ej2-angular-dropdowns',
  '@syncfusion/ej2-angular-grids',
  '@syncfusion/ej2-angular-inputs',
  '@syncfusion/ej2-angular-navigations',
  '@syncfusion/ej2-angular-notifications',
  '@syncfusion/ej2-angular-popups',
  '@syncfusion/ej2-angular-querybuilder',
  '@syncfusion/ej2-layouts'
]
Executing "npm install @syncfusion/ej2-angular-buttons@latest @syncfusion/ej2-angular-dropdowns@latest @syncfusion/ej2-angular-grids@latest @syncfusion/ej2-angular-inputs@latest @syncfusion/ej2-angular-navigations@latest @syncfusion/ej2-angular-notifications@latest @syncfusion/ej2-angular-popups@latest @syncfusion/ej2-angular-querybuilder@latest @syncfusion/ej2-layouts@latest"
```

The problem is that the npm install command is not getting executed at all. There is no change to package.json or to the installed packages.

Any ideas?

**Comment by beshanoe** [comment]
Could you provide an info on OS you’re using as well as node an npm versions and what terminal you use. Also, does it work if you copy the command from th output and runit in terminal? 
```
npm install @syncfusion/ej2-angular-buttons@latest @syncfusion/ej2-angular-dropdowns@latest @syncfusion/ej2-angular-grids@latest @syncfusion/ej2-angular-inputs@latest @syncfusion/ej2-angular-navigations@latest @syncfusion/ej2-angular-notifications@latest @syncfusion/ej2-angular-popups@latest @syncfusion/ej2-angular-querybuilder@latest @syncfusion/ej2-layouts@latest
```

**Comment by gs-scooter** [comment]
OS: Windows 10
Terminal: VSCode integrated terminal
NPM: 6.9.0
Node: 12.5.0

Yes, the output command works fine when run on its own.

**Comment by beshanoe** [comment]
It seems that the problem could be in the way child process creation works on windows, unfortunately I don't have a windows to debug, but I'll try to find the reason. Meanwhile if you can also find the cause and the way to solve it, would be great :)

**Comment by gs-scooter** [comment]
I think I figured it out. It's a matter of supplying the shell spawn option since it needs to be true for Windows. PR has been created.
